function [] = aggregatePlotting_v3(masterAngles, protocolWeightedMean, colors,...
    protocolStdErr,protocolChiFitPos, protocolChiFitNeg, linestyle,protocolNames, S,...
    axes)

for ii = 1:4
    scatter(masterAngles, protocolWeightedMean(ii,:), S{ii}, 'filled', 'MarkerFaceColor',...
       colors{ii}, 'MarkerEdgeColor', colors{ii}, 'LineWidth', 1);
    hold on;
    errorbar(masterAngles, protocolWeightedMean(ii,:),...
        protocolStdErr(ii,:), 'o', 'Color', colors{ii}, 'LineWidth', 1, 'Capsize', 0);
    hold on;
    plot(masterAngles(masterAngles>=0),masterAngles(masterAngles>=0)*...
        protocolChiFitPos(ii).slope + protocolChiFitPos(ii).intercept, 'LineWidth', 1,...
        'LineStyle', linestyle{ii}, 'color', colors{ii});
    hold on;
    plot(masterAngles(masterAngles<=0),masterAngles(masterAngles<=0)*...
        protocolChiFitNeg(ii).slope + protocolChiFitNeg(ii).intercept, 'LineWidth', 1,...
        'LineStyle', linestyle{ii}, 'color', colors{ii});
    hold on;
    xlabel(axes{1});
    ylabel(axes{2});
    box on;
    grid on;
    set(gcf, 'Position',  [20, 20, 700, 800]);
    h(ii) = plot(2000, 'LineWidth', 1, 'MarkerFaceColor', colors{ii}, 'color', colors{ii}, ...
     'LineStyle', linestyle{ii}, 'MarkerSize', 5, 'DisplayName', protocolNames{ii},...
     'Marker', S{ii}); hold on;
    legend(h, 'Location', 'Northeastoutside', 'AutoUpdate', 'off');
    xlim([(masterAngles(1)-5) (masterAngles(end)+5)]);
    ylim([100 900]);
end
